package frc.robot.ModesEnum;

public enum AutoEnum {
    ONE_CONE_LEAVE_COMMUNITY,
    ONE_CONE_BALANCE_CHARGE_STATION,
    ONE_CONE_SCORE_LOW_LEAVE_COMMUNITY,
    ONE_CONE_SCORE_LOW_CHARGE_STATION,
    BALANCE_ONLY, 
    DO_NOTHING,
    SCORE_MID_DO_NOTHING,
    SCORE_LOW_DO_NOTHING,
    LEAVE_COMMUNITY_ONLY
}




